### ISSUE TITLE
Bills since March 12, 2015 aren't being pulled in

### ISSUE THREAD

**Issue by pqnelson** [sunlightlabs/congress#497]
I tried GET-ing `hr1372-114`, but it's unavailable. It appears that no bill is available since March 12th (e.g., `hr1253-114` is not available either). 

Is there usually some delay?

**Addendum** it appears that only bills in the House of Representatives are not being pulled in...Senate bills show up fine. (Well, 18 of them show up as introduced since 2015-03-12)

**Comment by handlers** [comment]
Thanks for the heads. We've addressed the root cause (outdated version of a library) and the changes are starting to take effect: https://congress.api.sunlightfoundation.com/bills?chamber=house&apikey=YOURAPIKEY.
