### ISSUE TITLE
endpoint not working?

### ISSUE THREAD

**Issue by bschmoker** [sunlightlabs/congress#501]
`curl https://congress.api.sunlightfoundation.com/bills?congress=113&apikey=$my_key`

> {"error":"API key required, you can obtain one from http://services.sunlightlabs.com/accounts/register/","status":403}

It may be an issue with my API key, when using [the py bindings](https://python-sunlight.readthedocs.org/en/latest/index.html):
`sunlight.config.API_KEY = '$my_key'`

> {"error":"API key required, you can obtain one from http://services.sunlightlabs.com/accounts/register/","status":403}

**Comment by mileswwatkins** [comment]
@bschmoker: It looks like you have a malformed query string. Try the following instead, with only one question mark and an ampersand connecting the terms:
https://congress.api.sunlightfoundation.com/bills?congress=113&apikey=$my_key

**Comment by bschmoker** [comment]
@mileswwatkins oops, thanks! That's why it was returning the 'not found' thing.

Edited my prior post. Definitely looks like my key isn't working

**Comment by mileswwatkins** [comment]
If it's still failing, then your key might be the issue. You can test out your key in our GUI here:
http://tryit.sunlightfoundation.com/congress

**Comment by bschmoker** [comment]
Yep same result from `tryit` , looks like key is busted
