### ISSUE TITLE
Make it possible to get bill cosponsors in /bills/search/ response

### ISSUE THREAD

**Issue by okdan** [sunlightlabs/congress#502]
Currently if you make a query such as: http://congress.api.sunlightfoundation.com/bills/search?query=education&apikey=API_KEY

Your response will only include a cosponsor_count, not an array of their id's. Reading the documentation, it seems like if I explicitly request the cosponsor_id field on the request, I *should* get that array of IDs back. But that's not the case: http://congress.api.sunlightfoundation.com/bills/search?query=education&apikey=API_KEY&fields=cosponsor_ids

It's been suggested that this is an indexing issue on elasticsearch.

**Comment by jcarbaugh** [comment]
@okdan we'll be pushing this change out shortly, after we push and reindex.
