### ISSUE TITLE
Senate Hearings missing

### ISSUE THREAD

**Issue by pqnelson** [sunlightlabs/congress#504]
Hello,

So Senate hearings appear to be missing, e.g., 

- Who: the Senate Appropriations: Subcommittee on Transportation, Housing and Urban Development, and Related Agencies
- What: Business meeting to markup an original bill entitled, "Transportation, Housing and Urban Development, and Related Agencies Appropriations Act, 2016"
- ID from the Senate.gov page: SD-138 

This is not in the Sunlight system, despite the fact that it is on the [upcoming Senate hearings page](http://www.senate.gov/pagelayout/committees/b_three_sections_with_teasers/committee_hearings.htm).

There are other Senate hearings which are missing too...so what's up?

Thanks,
Alex

**Comment by handlers** [comment]
@pqnelson I am showing those hearings in the API, now. Are you? 

Perhaps it was lag on the part of our scrapers, or maybe the Senate site was updated but the [XML](http://www.senate.gov/general/committee_schedules/hearings.xml) (which is what we scrape) wasn't?

**Comment by pqnelson** [comment]
I just tried fetching the hearings. The Senate hearing from [senate.gov](http://www.senate.gov/pagelayout/committees/b_three_sections_with_teasers/committee_hearings.htm) for July 9th is missing:

> Thursday, Jul. 09, 2015
> 10:00 AM
>    	Energy and Natural Resources
>    	    	An oversight hearing to examine mitigation requirements, interagency coordination, and pilot projects related to economic development on Federal lands.
> SD-366 

This *is* in the XML:

```xml
<meeting>
  <cmte_code>SSEG00</cmte_code>
  <committee url="http://www.energy.senate.gov/">Energy and Natural Resources</committee>
  <date>09-JUL-2015 10:00 AM</date>
  <day_of_week>Thursday</day_of_week>
  <time>10:00 AM</time>
  <room>SD-366</room>
  <matter>An oversight hearing to examine mitigation requirements, 
  interagency coordination, and pilot projects related to economic 
  development on Federal lands.</matter>
</meeting>
```

And it has been there for a few days. This is weird, because the next hearing *has* been crawled (the "Hearings to examine the back-end of the nuclear fuel cycle and related legislation, including S.854, to establish a new organization to manage nuclear waste, provide a consensual process for siting nuclear waste facilities, ensure adequate funding for managing nuclear waste." with hearing id "ed665087bee3233b3539d0cc464f1c92").

Neither is the Judiciary's Crime and Terrorism Subcommittee hearing on 8 July 2015 "Hearings to examine cyber crime, focusing on modernizing our legal framework for the information age" in the system.

**Comment by handlers** [comment]
I'm showing these hearings if I order the query results by `occurs_at`: 

`https://congress.api.sunlightfoundation.com/hearings?order=occurs_at&chamber=senate&apikey=FOOBAR`

July 9 (economic development on federal lands):
```
{
committee_id: "SSEG",
congress: 114,
room: "SD-366",
dc: true,
bill_ids: [ ],
chamber: "senate",
hearing_id: "2395ad5f2e66025d0b89b07d48f4c4a7",
occurs_at: "2015-07-09T14:00:00Z",
description: "An oversight hearing to examine mitigation requirements, interagency coordination, and pilot projects related to economic development on Federal lands."
},
```

July 8 (cybercrime)
```
{
committee_id: "SSJU",
congress: 114,
description: "Hearings to examine cyber crime, focusing on modernizing our legal framework for the information age.",
dc: true,
bill_ids: [ ],
chamber: "senate",
subcommittee_id: "SSJU22",
hearing_id: "8d5d48a8f56ee127c7fe293b61a558a3",
occurs_at: "2015-07-08T18:15:00Z",
room: "SD-226"
},
```

**Comment by pqnelson** [comment]
Hello, I believe I have found the problem--my predecessor was using "per_page=all", which appears to have caused problems. After removing this from the query, a flood of hearings rain down into my system.

Thank you so much for you patience.

**Comment by handlers** [comment]
No problem — closing the issue!
