### ISSUE TITLE
Request all legislators?

### ISSUE THREAD

**Issue by JuanCaicedo** [sunlightlabs/congress#518]
If I make a request to `/legislators` I get back one response with a `"results"` array of 20 legislators. Is it possible to load all legislators? 

I would think that I can provide an offset in my request to get legislators 21-40, then just keep making calls until I have all of them. However, I couldn't find it in the documentation.

**Comment by JuanCaicedo** [comment]
Never mind, I found that you can pass `page=<number>` to any request to get the next page.

**Comment by konklone** [comment]
For `/legislators` only, you can pass `per_page=all` to get them all at once, instead of having to paginate through.

**Comment by JuanCaicedo** [comment]
Great, thanks @konklone !
